# Generated by Django 4.0.6 on 2022-12-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
